<a href="https://colab.research.google.com/github/Alexismenethil/PyTorch-Tutorial_I/blob/main/intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np


lists

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

numpy arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.01229786, 0.48199745, 0.35696419, 0.82780586],
       [0.06508878, 0.78407939, 0.21849273, 0.75041236],
       [0.83661516, 0.69573312, 0.80260054, 0.44626717]])

In [9]:
np1.dtype


dtype('float64')

Tensors

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0123, 0.4820, 0.3570, 0.8278],
        [0.0651, 0.7841, 0.2185, 0.7504],
        [0.8366, 0.6957, 0.8026, 0.4463]], dtype=torch.float64)